version: 0.2


phases:
  install:
      runtime-versions:
       nodejs: 14
      commands:
       - echo install serverless framework
       #- npm install -g serverless
  pre_build:
    commands:
      - echo install pre build commands
  build:
    commands:
      - echo deployment started `date`
      - echo deploy serverless framework custom codebase
      - npm install
      - npm run test
artifacts:
   files:
    - '**/*'
post_build:
   commands:
      - echo post build completed on `date`
